version: '2.1'
services:
  appsvr:
    #image: 38leinad/wlp-javaee7-jdbc:latest
    #image: openliberty/open-liberty:javaee7
    image: websphere-liberty:javaee7
    ports:
     - "80:9080"
    volumes:
     - "./target/jee-00.war:/config/dropins/jee-00.war"
    healthcheck:
      test: wget --quiet --tries=1 --spider http://localhost:9080/jee-00/resources/health || exit 1
      interval: 5s
      timeout: 10s
      retries: 3